name: Linters (flake8, black, isort)

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.3.0
        with:
          python-version-file: '.python-version'
      - uses: pre-commit/action@v3.0.1
